### PR TITLE
refactor(native): uncomment return type t

### LINKED ISSUE #29: Expose `type t` for native
Hey @baransu, thanks for porting this for native as well, works great! 

One thing I'm missing right now is the fact that `t` is not exposed. I noticed that there seemed to be some magic involved in order to get the return-type which looks commented out in the native-code. Did you run into issues with it? Can I help?

EDIT:

As discussed in Discord, I think this might be related: <https://github.com/baransu/graphql_ppx_re/blob/master/src/native/output_native_module.re#L229>
<https://github.com/baransu/graphql_ppx_re/blob/master/src/native/output_native_module.re#L280>
<https://github.com/baransu/graphql_ppx_re/blob/master/src/native/output_native_module.re#L30>

### PR DESCRIPTION
**Pull request by lessp**
OK, so locally it seems as this works to expose `t`. One would think there's a reason for it being commented out, but I haven't hit any issues yet. 🤷‍♂ 

Would fix #29

### CODE REVIEW

**Comment by baransu** [comment]
Looks good to me. Thank you @lessp 🎉

I see that CI is failing. It's not connected to the PR itself but if you have spare few minutes would be great if you could make it working again 😉

**Comment by lessp** [comment]
> Looks good to me. Thank you @lessp 🎉
> 
> I see that CI is failing. It's not connected to the PR itself but if you have spare few minutes would be great if you could make it working again 😉

The issue with CI seems to be that Windows (or the version runnign in CI) can't handle `&&`, splitting them to separate lines seems to do the trick.

With that said, the following test seems to fail with this change (`return t`):

```
// tests/native/custom_scalars.re

Error: The type of this packed module contains variables:
< customScalarField : < nonNullable : [> `Null ];
                        nullable : [> `Null ] option > >
typed_ret
```

**Comment by baransu** [comment]
@lessp Because in OCaml type system poly variants can be open (e.g ```[> `Null]```), return type magic could not figure out the exact type of the `parse` function. The fix was to explicit mark all ``` `Null``` values as `Yojson.Basic.t`.

**Comment by baransu** [comment]
Quick example in smaller scale: https://sketch.sh/s/JUxWzw49tzhRmPZMeQcWs6/

**Comment by baransu** [comment]
LGTM 🎉 Thank you @lessp

**Pull request merged**
