### PR TITLE
Support configuration via ppx-flags

### LINKED ISSUE #40: Support configuration in bsconfig.json
I've tried to change from graphql_ppx to graphql_ppx_re and ran into an issue where none of my configuration values provided in `bsconfig.json` are supported. I previously had used the following:

```
"ppx-flags": [
   ["graphql_ppx/ppx", "-verbose", "-apollo-mode", "-schema=src/graphql/schema.json"]
]
```

I see in the README that there are `GRAPHQL_PPX_APOLLO_MODE` and `GRAPHQL_PPX_SCHEMA` environment variables to support some of this functionality. However, it's considerably more convenient to have this as part of the checked-in source code where it can be managed per-project. Additionally, the BuckleScript build configuration docs [recommend not using environment variables for build configuration](https://bucklescript.github.io/docs/en/build-configuration.html#environment-variables).

If the ability to pass command-line arguments won't be reinstated, I think it'd be helpful to document how to migrate from `graphql_ppx`.

### PR DESCRIPTION
**Pull request by baransu**
When migrating to the current version of `Migrate_parsetree` I've removed `ppx-flags` based configuration (i.e ppx arguments).

This PR resolves #40 brings back configuration in `ppx-flags` in `bsconfig.json` and removes support for env variables. It's a breaking change and will result in "major" version bump (i.e minor because of pre 1.0.0 versioning we're using right now).

### CODE REVIEW

**Comment by anmonteiro** [comment]
woohoo @baransu great job on this

**Comment by jfrolich** [comment]
Nice one!!

**Comment by baransu** [comment]
I'll merge that and release it over the weekend.

**Comment by nirvdrum** [comment]
Fantastic. Thanks!

**Pull request merged**
