### PR TITLE
Support OCaml 4.08+

### LINKED ISSUE #22: OCaml 4.08+ support
Thanks for getting this project moving. Right now it doesn't seem like it's possible to depend on this package in newer versions of OCaml. I had to add the following to my esy resolutions:

```json
    "@baransu/graphql_ppx_re": {
      "source": "baransu/graphql_ppx_re:esy.json#c7fab6c",
      "override": {
        "build": "dune build -p graphql_ppx",
        "dependencies": {
          "@opam/ocaml-migrate-parsetree": "*",
          "@esy-ocaml/reason": "*",
          "refmterr": null
        }
      }
    }
```

I think these could get integrated in master. I don't know what refmterr is but it just doesn't build on OCaml 4.09 which is what I was testing, and removing it works fine. The `esy.json` also looks weird, and many of its dependencies are _very_ outdated (e.g. Menhir, OMP). I can submit an enhancement PR if you want.

### PR DESCRIPTION
**Pull request by anmonteiro**
Fixes #22

### CODE REVIEW

**Comment by anmonteiro** [comment]
@baransu I think you might need to enable building PRs on the CI you're using

**Comment by baransu** [comment]
@anmonteiro Not sure if it triggered because of my push or correct GH Action config. Thank you for the PR!

**Comment by anmonteiro** [comment]
@baransu so the only problem with this PR now is that it might get harder for you to release for 4.06, as I'm bumping the OCaml dep in esy.json to 4.09. Perhaps we should maintain a 406.json file?

**Comment by baransu** [comment]
Yes, its a best solution. 402.json for BuckleScript 5, 406.json for BuckleScript 6 and esy.json for native development with latest OCaml. Could you please adjust the PR to that?

**Comment by baransu** [comment]
Closing in favor of #47

**Pull request closed without merging**
