### PR TITLE
Updating BuckleScript tests suite

### PR DESCRIPTION
**Pull request by Fanneyyy**
### What
- Excludes warning 32 as error in BuckleScript tests
- Updates the README on how to run the BuckleScript tests
- Removes `react-jsx` from the `bsconfig` tests

### Why
- Because the interface files were causing unused variable errors and failing the tests
- There's no `react-jsx` in the tests

### CODE REVIEW

**Comment by baransu** [comment]
Thank you for removing `react-jsx` and updating README.

> Because the interface files were causing unused variable errors and failing the tests

Strange, I haven't experienced it nor the CI complains. Was it because of unused variables warning in `bsconifg`? AFAIK it shouldn't be an issue as it's set only to warning at most.

**Comment by Fanneyyy** [comment]
The [bsconfig](https://github.com/baransu/graphql_ppx_re/blob/master/tests_bucklescript/bsb6/bsconfig.json) is not excluding error 32, we can add it if we prefer keeping the interface files?

**Comment by Fanneyyy** [comment]
@baransu Reverted the removal of the interface files, not sure why this was not failing in CI but added the warning 32 in the bsconfig excludes because otherwise it failed locally, hope that's okay?

**Comment by baransu** [comment]
That sounds ok 🙂 Thank you a lot for changes 🎉

**Pull request merged**
