### PR TITLE
Increase performance of nested queries

### PR DESCRIPTION
**Pull request by johnhaley81**
With nested queries the code was switching on the option so that it
could display a custom message. This was causing a massive increase in
compilation time as the queries got deeper and wider. In my project we
were seeing build times of about 6 minutes, after this change the build
went down to about 10-11 seconds.

Instead of displaying a custom message, the PPX will now just call out
to `Js.Option.getExn`.

### CODE REVIEW

**Comment by johnhaley81** [comment]
I ported this PR over from https://github.com/mhallin/graphql_ppx/pull/85 and this should also fix #27 

I'm unable to run the tests locally so if I could get some guidance that would be really appreciated :D

**Comment by johnhaley81** [comment]
I got the tests to run and things look good! I also was able to manually-inspect the generated JS which looks correct. I think this is gtg.

**Comment by baransu** [comment]
Could you please rebase to master. I've pushed some fixes to how tests are run and it should trigger GH Actions for this PR.

**Comment by johnhaley81** [comment]
@baransu done!

**Comment by shinzui** [comment]
I would love to see this merged. It fixes the slow compile times and the generated code size in our project.

**Pull request merged**
